version: "2"
linters:
  default: all
  disable:
    - revive
    - depguard
    - tagliatelle
    - wsl # deprecated
    - musttag
  settings:
    ireturn:
      allow:
        - ResponseObject$
        - error
        - empty
    varnamelen:
      min-name-length: 2