version: "2"
linters:
  default: all
  disable:
    - revive
    - depguard
    - tagliatelle
    - wsl # deprecated
    - musttag
    - prealloc
    - ireturn # 버그 있음. auto fix할 때, 이상하게 동작해서 일단 제거
  settings:
    varnamelen:
      min-name-length: 2